language: ruby
rvm:
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - ruby-head
  - jruby-head
  - ree
deploy:
  provider: heroku
  app: chrismontes # optional if it's the same as your repo name
  api_key: "09a98fb7ca323199ea70b329410ed839ad2f2095"
  run: "rake db:migrate"
