language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
deploy:
  provider: heroku
  app: chrismontes # optional if it's the same as your repo name
  api_key: "09a98fb7ca323199ea70b329410ed839ad2f2095"
  run: "rake db:migrate"
