language: ruby
rvm:
- 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: Q9Ch1k2F97jprmIO0jQvBoVyod48xmX7XlHcmW6VIUdjbDMIPj8IL/7EVxvwdN8/ki79nwDVOhY3uzCwtz0Y3dh9B3Y5PV43kg0QClWHPTgKJUktGQ6phuzwlCTXUW843nUQmIq5BRPBRw1oE3RSlhOYEGTziNXzNalUwAIaleY=
  app: chrismontes
  on:
    repo: mandelbro/ROR2014-portfolio
    branch: master
    rvm: 2.0.0
  run:
  - bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin
    -j4 --deployment
  - rake db:migrate
  - restart
before_script:
- psql -c 'create database portfolio_test' -U postgres
- bundle exec rake db:migrate
env:
  matrix:
  - DB=postgresql
  global:
    secure: K4ESBXbpurqPuRBjVP7fYy5G2PwcuWGB0VRB+gp8ey59J/6yfiP5JDKDb/+gNTx4GY2+PKNc6Ol2zT7JykaWl3UP5noQHMZmAh1faM3FGHAGXyrxFBlgI+95/UUkjNivzGARBuPIz/3/W1IDy0UKzd24Sl2E1LQkoaFvio5MfHU=
